### ISSUE TITLE
firebase-functions not found

### ISSUE THREAD

**Issue by matthiasbruns** [jthegedus/blog-code#3]
## Which Package & Your Environment

After I cloned the repo as written in the readme and follow the instructions (change project-id, yarn, yarn serve), the following error occurs:

```
[warn] ⚠  functions: Failed to load functions source code. Ensure that you have the latest SDK by running npm i --save firebase-functions inside the functions directory.
[debug] [2018-04-04T11:28:04.306Z] Error during trigger parsing:  Error parsing triggers: Cannot find module '/Users/xxx/Development/xxx/firebase-functions-es6-babel/dist/functions'

Try running "npm install" in your functions directory before deploying.
[warn] ⚠  functions: Error from emulator. Error parsing triggers: Cannot find module '/Users/xxx/Development/xxx/firebase-functions-es6-babel/dist/functions'

Try running "npm install" in your functions directory before deploying.
```

## Expected Behaviour

Serve works without further configurations.

## Actual Behaviour

Serve does not run.

## Possible Solution

Can't find a solution yet.

## Context

Clean repo clone.

**Comment by jthegedus** [comment]
hmm, I will look into this further. I've got to do some cleanup now the Firebase Functions v1.0 has been released with fixes for the emulator etc.

Thanks for taking the time to write this up :smile:

**Comment by siriwatknp** [comment]
I face this issue too, any work around?
